using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace RapidLinkGetter
{
    class YunData
    {
        public string ALBUMTITLE;
        public string ARTISTNAME;
        public string CATEGORY;
        public string CFROMID;
        public string CTIME;
        public string CURRACTIVITYCODE;
        public string DOCPREVIEW;
        public string FILEINFO;
        public string FILENAME;
        public string FIRST_FILE_SIZE;
        public string FOLLOWFLAG;
        public string FS_ID;
        public string HIT_OGC;
        public string ISFIRST;
        public string ISSVIP;
        public string ISVIP;
        public string ISYEARVIP;
        public string IS_BAIDUSPIDER;
        public string LOGINSTATUS;
        public string LRURPVSDB;
        public string MYAVATAR;
        public string MYBDSTOKEN;
        public string MYBDUSS;
        public string MYNAME;
        public string MYSELF;
        public string MYUK;
        public string NOVELID;
        public string PANSUK;
        public string PATH;
        public string PATH_MD5;
        public string SAMPLING;
        public string SERVERTIME;
        public string SHAREPAGETYPE;
        public string SHAREVIPLEVEL;
        public string SHAREVIPTYPE;
        public string SHARE_DESCRIPTION;
        public string SHARE_ID;
        public string SHARE;
        public string SHARE_TIME;
        public string SHARE_UK;
        public string SHARE_USER_NAME;
        public string SHOWVIPAD;
        public string SIGN;
        public string TIMESTAMP;
        public string TRACKTITLE;
        public string UINFO;
        public string VIPENDTIME;
        public string VIPLEVEL;
        public string VIPTYPE;
        public string activity_end_time;
        public string addFriendSmallFlow;
        public string errortype;
        public string faceStatus;
        public string getPrimitiveValue;
        public string is_company;
        public string openlogo;
        public string openyy;
        public string sign1;
        public string sign2;
        public string sign3;
        public string sign4;
        public string sign5;
        public string skinName;
        public string task_key;
        public string task_time;
        public string timestamp;
        public string title_img;
        public string token;
    }
}
